# Format data - Casillas

In [1]:
import numpy as np
import pandas as pd

## Parámetros

In [ ]:
dict_entidad = {
    "Aguascalientes": "01",
    "Baja California": "02",
    "Baja California": "02",
    "Baja California Sur": "03",
    "Campeche": "04",
    "Coahuila de Zaragoza": "05",
    "Coahuila de Zaragoza": "05",
    "Coahuila de Zaragoza": "05",
    "Coahuila de Zaragoza": "05",
    "Colima": "06",
    "Chiapas": "07",
    "Chiapas": "07",
    "Chihuahua": "08",
    "Chihuahua": "08",
    "Chihuahua": "08",
    "Ciudad de México": "09",
    "Durango": "10",
    "Guanajuato": "11",
    "Guanajuato": "11",
    "Guerrero": "12",
    "Guerrero": "12",
    "Hidalgo": "13",
    "Hidalgo": "13",
    "Jalisco": "14",
    "Jalisco": "14",
    "México": "15",
    "México": "15",
    "Michoacán de Ocampo": "16",
    "Michoacán de Ocampo": "16",
    "Morelos": "17",
    "Nayarit": "18",
    "Nuevo León": "19",
    "Oaxaca": "20",
    "Oaxaca": "20",
    "Puebla": "21",
    "Puebla": "21",
    "Queretaro": "22",
    "Quintana Roo": "23",
    "Quintana Roo": "23",
    "San Luis Potosí": "24",
    "Sinaloa": "25",
    "Sonora": "26",
    "Sonora": "26",
    "Sonora": "26",
    "Tabasco": "27",
    "Tamaulipas": "28",
    "Tamaulipas": "28",
    "Tlaxcala": "29",
    "Veracruz de Ignacio de la Llave": "30",
    "Veracruz de Ignacio de la Llave": "30",
    "Veracruz de Ignacio de la Llave": "30",
    "Veracruz de Ignacio de la Llave": "30",
    "Yucatán": "31",
    "Zacatecas": "32",
    "Zacatecas": "32",
}

#### Funciones

In [34]:
def gets_secciones_atendidas(casillas_df):
    """
    Gets a list of the sections that are being attended

    Parameters
    ----------
    casillas_df : dataframe
        Dataframe with the casillas data

    Returns
    -------
    list
        List of sections that are being attended per casilla
    """
    unique_domicilios = list(casillas_df['domicilio'].unique())
    vector_secciones = []

    for unique_domicilio in unique_domicilios:
        df_casilla = casillas_df[casillas_df['domicilio'] == unique_domicilio].copy()
        secciones_atendidas = list(df_casilla['seccion'].unique())
        str_secciones_atendidas = str(secciones_atendidas).replace('[', '').replace(']', '')
        # Agregar n veces el vector de secciones
        for n in list(df_casilla['seccion']):
            vector_secciones.append(str_secciones_atendidas)

    return vector_secciones

### Pipeline

In [35]:
casillas_df = pd.read_csv("casillas_edos-1-32.csv", encoding='utf-8-sig')
casillas_df.head(n=10)

,casilla,inicial,final,domicilio,ubicacion,entidad,distitoSede,distritoLocal,latitud,longitud,seccion
0,B,ABOYTES DOÑAS,LLAMAS DELGADO,"CALLE HUIZACHE, NÚMERO 108, FRACCIONAMIENTO EL...",DOMICILIO PARTICULAR,1,3,6,-102.321935,21.929537,1
1,C1,LLAMAS ESPERON,ZUÑIGA GONZALEZ,"CALLE HUIZACHE, NÚMERO 108, FRACCIONAMIENTO EL...",DOMICILIO PARTICULAR,1,3,6,-102.321935,21.929537,1
2,B,ABREGO GUTIERREZ,LLAMAS VAZQUEZ,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,2
3,C1,LOERA CHAVEZ,ZURITA ALVARADO,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,2
4,B,ABREGO GUTIERREZ,LLAMAS VAZQUEZ,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,4
5,C1,LOERA CHAVEZ,ZURITA ALVARADO,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,4
6,B,ABREGO GUTIERREZ,LLAMAS VAZQUEZ,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,5
7,C1,LOERA CHAVEZ,ZURITA ALVARADO,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,5
8,B,ABREGO GUTIERREZ,LLAMAS VAZQUEZ,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,6
9,C1,LOERA CHAVEZ,ZURITA ALVARADO,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,6

In [37]:
vector_secciones = gets_secciones_atendidas(casillas_df)

In [38]:
casillas_df['seccionesAtendidas'] = vector_secciones

In [40]:
casillas_df

,casilla,inicial,final,domicilio,ubicacion,entidad,distitoSede,distritoLocal,latitud,longitud,seccion,seccionesAtendidas
0,B,ABOYTES DOÑAS,LLAMAS DELGADO,"CALLE HUIZACHE, NÚMERO 108, FRACCIONAMIENTO EL...",DOMICILIO PARTICULAR,1,3,6,-102.321935,21.929537,1,1
1,C1,LLAMAS ESPERON,ZUÑIGA GONZALEZ,"CALLE HUIZACHE, NÚMERO 108, FRACCIONAMIENTO EL...",DOMICILIO PARTICULAR,1,3,6,-102.321935,21.929537,1,1
2,B,ABREGO GUTIERREZ,LLAMAS VAZQUEZ,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,2,"2, 4, 5, 6"
3,C1,LOERA CHAVEZ,ZURITA ALVARADO,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,2,"2, 4, 5, 6"
4,B,ABREGO GUTIERREZ,LLAMAS VAZQUEZ,"AVENIDA GUADALUPE GONZÁLEZ, SIN NÚMERO, COLONI...",AULA MAGNA DEL DESARROLLO INTEGRAL DE LA FAMIL...,1,3,6,-102.311723,21.909189,4,"2, 4, 5, 6"
...,...,...,...,...,...,...,...,...,...,...,...,...
151490,C1,DIAZ SANTOS,PECH CAAMAL,"CALLE 17 POR 22 B Y 10 A, SIN NÚMERO, COLONIA ...",ESCUELA SECUNDARIA TÉCNICA NÚMERO 2 RAQUEL DZI...,31,5,8,-89.737702,20.889688,1132,"1132, 991"
151491,C2,PECH CAAMAL,ZUÑIGA ISLAS,"CALLE 17 POR 22 B Y 10 A, SIN NÚMERO, COLONIA ...",ESCUELA SECUNDARIA TÉCNICA NÚMERO 2 RAQUEL DZI...,31,5,8,-89.737702,20.889688,1132,"1132, 991"
151492,B,ABAN ABAN,DIAZ SANTOS,"CALLE 17 POR 22 B Y 10 A, SIN NÚMERO, COLONIA ...",ESCUELA SECUNDARIA TÉCNICA NÚMERO 2 RAQUEL DZI...,31,5,8,-89.737702,20.889688,991,"1132, 991"
151493,C1,DIAZ SANTOS,PECH CAAMAL,"CALLE 17 POR 22 B Y 10 A, SIN NÚMERO, COLONIA ...",ESCUELA SECUNDARIA TÉCNICA NÚMERO 2 RAQUEL DZI...,31,5,8,-89.737702,20.889688,991,"1132, 991"
151494,C2,PECH CAAMAL,ZUÑIGA ISLAS,"CALLE 17 POR 22 B Y 10 A, SIN NÚMERO, COLONIA ...",ESCUELA SECUNDARIA TÉCNICA NÚMERO 2 RAQUEL DZI...,31,5,8,-89.737702,20.889688,991,"1132, 991"